deprecation and redirect notice
tstirrat/ucm-maven-plugin pull request #4
Opened 2017-04-24 17:04 UTC by raystorm

Adds a header that points out that this project is no longer being maintained as well a link to my project.

2017-07-07 18:35 UTC, raystorm commented
@tstirrat

Just a poke.

2017-07-08 18:10 UTC, tstirrat requested changes

2017-07-08 18:10 UTC, tstirrat commented on readme.md
> +This project has been discontinued and is no longer in activre development.
active* development

2017-07-10 12:56 UTC, raystorm commented
Spelling corrected.

2017-07-11 00:34 UTC, merged